version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: poseidon
      POSTGRES_DB: medusa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: medusa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
